/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ABCD;

/**
 *
 * @author User
 */
public class Mainmenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mainmenu.class.getName());

    /**
     * Creates new form Mainmenu
     */
    public Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Customer = new javax.swing.JMenuItem();
        account = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Deposit = new javax.swing.JMenuItem();
        Withdrow = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Account = new javax.swing.JMenuItem();
        CustomerRe = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        BalnceCheck = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        back = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane2.setBackground(new java.awt.Color(0, 51, 51));
        jDesktopPane2.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        Customer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Customer.setText("Customer");
        Customer.addActionListener(this::CustomerActionPerformed);
        jMenu1.add(Customer);

        account.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        account.setText("Account");
        account.addActionListener(this::accountActionPerformed);
        jMenu1.add(account);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaction");

        Deposit.setText("Diposit");
        Deposit.addActionListener(this::DepositActionPerformed);
        jMenu2.add(Deposit);

        Withdrow.setText("Withdraw");
        Withdrow.addActionListener(this::WithdrowActionPerformed);
        jMenu2.add(Withdrow);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transfer");

        Account.setText("Account to Account");
        Account.addActionListener(this::AccountActionPerformed);
        jMenu3.add(Account);

        jMenuBar1.add(jMenu3);

        CustomerRe.setText("Reports");

        jMenuItem7.setText("Customers Reports");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        CustomerRe.add(jMenuItem7);

        jMenuBar1.add(CustomerRe);

        BalnceCheck.setText("Balance");

        jMenuItem8.setText("Balance Check");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        BalnceCheck.add(jMenuItem8);

        jMenuBar1.add(BalnceCheck);

        jMenu6.setText("Account");

        jMenuItem9.setText("User Account");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Back");

        back.setText("Back to login page");
        back.addActionListener(this::backActionPerformed);
        jMenu7.add(back);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
        Customer cus = new Customer();
        jDesktopPane2.add(cus);
        cus.setVisible(true);
        
    }//GEN-LAST:event_CustomerActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
account acc = new account();
    jDesktopPane2.add(acc);
    acc.setVisible(true);        
    }//GEN-LAST:event_accountActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
       Deposit dep = new Deposit();
    jDesktopPane2.add(dep);
    dep.setVisible(true);
    }//GEN-LAST:event_DepositActionPerformed

    private void WithdrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrowActionPerformed
        Withdrow wd = new Withdrow();
    jDesktopPane2.add(wd);
    wd.setVisible(true);
    }//GEN-LAST:event_WithdrowActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       Login log = new Login();
    log.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        Transfer tr = new Transfer();
    jDesktopPane2.add(tr);
    tr.setVisible(true);
    }//GEN-LAST:event_AccountActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       CustomerReport cusReport = new CustomerReport();
jDesktopPane2.add(cusReport);
cusReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       Balance b = new Balance();
    jDesktopPane2.add(b);
    b.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Useraccount ua = new Useraccount();
jDesktopPane2.add(ua);
ua.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mainmenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Account;
    private javax.swing.JMenu BalnceCheck;
    private javax.swing.JMenuItem Customer;
    private javax.swing.JMenu CustomerRe;
    private javax.swing.JMenuItem Deposit;
    private javax.swing.JMenuItem Withdrow;
    private javax.swing.JMenuItem account;
    private javax.swing.JMenuItem back;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
